# Makefile for solaris OS

# Use gcc

CC=gcc

CCFLAGS = -O4 -g

DEFS = -DUSE_READLINE
LDFLAGS = -lreadline -ltermcap

# Object file extension
OBJ = .o

# Physical I/O module
PHYSIO = phyunix
PHYSIOH =

include makefile.generic

clean:
	rm -f ods2 $(OBJS)
