
# Makefile for Windows NT
#

CCFLAGS = "-Oxs"

# For the direct SCSI module
#DEFS = -DUSE_WNASPI32
#LDFLAGS = wnaspi32.lib
#PHYSIOH = wnaspi32.h scsidefs.h
#LIBS = wnaspi32.lib

OBJ = .OBJ
PHYSIO = phynt

include makefile.generic

wnaspi32.lib : wnaspi32.def
	LIB /DEF:WNASPI32.DEF /MACHINE:IX86

clean:
    del $(OBJS)
    del ods2.exe
