# Makefile for most Unix distributions
#

CCFLAGS = -O4 -g
#-O0 -g -DUSE_READLINE -Wall -pedantic
# Extra warns about $ in identifiers...
#  -Wextra

# Include readline support

DEFS = -DUSE_READLINE
LDFLAGS = -lreadline -ltermcap

# Object file extension
OBJ = .o

# Physical I/O module
PHYSIO = phyunix
PHYSIOH =

include makefile.generic

clean:
	rm -f ods2 ods2i $(OBJS)
