# -*- Makefile -*-

# Makefile for Tru64 (DEC/OSF1)
#

CCFLAGS = -O4 -g

# DEFS = -DUSE_READLINE
# LDFLAGS = -lreadline -ltermcap

# Include VHD format image file support

VHDOPTS = makefile-vhd.unix

# Object file extension
OBJ = .o

DELETE  = rm -f

# Physical I/O module
PHYSIO = phyunix
PHYSIOH =

TOPMAKE = makefile.tru64

all:

clean:
	rm -f ods2 $(OBJS)

include makefile.generic
