;;;;;
;
; Test long local labels
;

lab1:   beq     1$
1$:     bne     lab1

; -- new scope
    
lab2a:  beq     12345$
12345$: bne     lab2a

; -- new scope
    
lab2b:  beq     12345$
12345$: bne     lab2b

; -- new scope

lab3:   beq     1$
1$:     bne     2$
2$:     beq     3$
3$:     beq     4$
4$:     beq     lab3

; -- new scope

lab4:   beq     1$
1$:     bne     2$
2$:     beq     3$
3$:     beq     4$
4$:     beq     lab4

; -- test if next pass sets this back to default (off)
;    also test that normal labels don't delimit local ones

	.enabl	lsb

1$:     bne     2$
2$:     beq     3$
lab5:   beq     1$
3$:     beq     4$
4$:     beq     lab5

        .end
